### ISSUE TITLE
公众号消息template_id错误

### ISSUE THREAD

**Issue by wanderpub** [rxrddd/austin-go#1]
这个项目非常好，但是发送公众号消息的时候传入的template_id是错误的，不应该取数据库中的ID，而应该是微信公众号的模版消息ID。

**Comment by rxrddd** [comment]
> 这个项目非常好，但是发送公众号消息的时候传入的template_id是错误的，不应该取数据库中的ID，而应该是微信公众号的模版消息ID。

传入数据库的id是没问题的，当时做这个的时候`officialAccountHandler`有一个`getRealWxMpTemplateId`方法是根据自己的业务拿到这个模板应该发送的真实的微信模板ID只是当时没往后做

**Comment by wanderpub** [comment]
OK

**Comment by wanderpub** [comment]
是不是可以在message_template表增加一个字段，因为这个模板ID用的地方还挺多的，发微信消息要用，发短信阤可能用到这个ID

**Comment by rxrddd** [comment]
> 是不是可以在message_template表增加一个字段，因为这个模板ID用的地方还挺多的，发微信消息要用，发短信也可能用到这个ID

感谢您的建议和PR
